### ISSUE TITLE
it cannot allow to register

### ISSUE THREAD

**Issue by dhernandezgt** [AllanScala1991/Secret_Key_EEL#1]
Hi Allan,

this is Daniel, I see your project very interesting and informative, I cloned it but once I tried to register it return a error that it is necessary to fill all fields out, even I re-wrote them is still returning same error.
Console it said db cannot open, it is missing the file in "views/database/storage.db", it can create from the files shared.

thanks for share it you grate work.

PD. by any chance, do you speak Spanish?

**Comment by dhernandezgt** [comment]
I translated note 1 and found it, great development. please contact me, my email is dhernandezgt@gmail.com for share some ideas.
Best Regards
DH

**Comment by AllanScala1991** [comment]
Hi dhernandezgt, 
The project really must have some bugs, I apologize for that.
